name: travel_forge
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy=1.26.4
  - pandas=2.1.4
  - scipy=1.15.1
  - scikit-learn=1.6.1
  - matplotlib-base=3.10.0
  - seaborn=0.13.2
  - tensorflow=2.10.0
  - pytorch=2.3.1
  - flask=3.1.0
  - fastapi
  - uvicorn
  - jinja2
  - sqlalchemy=2.0.37
  - alembic
  - pyyaml
  - python-dateutil
  - requests
  - pip:
      - gradio==5.22.0
      - transformers==4.50.3
      - sentence-transformers==4.0.1
      - evaluate==0.4.0
      - datasets==3.5.0
      - accelerate==1.6.0
      - mlflow==2.21.0
      - mlflow-skinny==2.21.0
      - orjson
      - ruff
